[package]
name = "hotwarm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.10.0"
rand = "0.8.5"
rand_xorshift = "0.3.0"
indicatif = "0.17.2"
redb = "0.11.0"
